### ISSUE TITLE
How to Use

### ISSUE THREAD

**Issue by AidanG1** [PatWie/svelte-konvajs#1]
I'm interested in using this package but when importing: import {Stage} from "svelte-konvajs"; I get the following error

Failed to resolve entry for package "svelte-konvajs". The package may have incorrect main/module/exports specified in its package.json: Missing "." export in "svelte-konvajs" package

I'm not sure if I'm doing everything correctly since the examples on the website import from $lib. When copy and pasting the files I used, everything worked so I assume it is a packaging issue.

Thanks for your time.

**Comment by pheianox** [comment]
What's a good question for maintainers!

**Comment by PatWie** [comment]
Doesn't it work when running `python generate.py` and `npm run dev`. If so this would be a packaging problem.

**Comment by AidanG1** [comment]
Oh. Didn't realize I had to run python generate.py. Thanks for the help.
